service: graphql-server

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    port: 4000

provider:
  name: aws
  region: eu-central-1
  stage: production
  runtime: nodejs8.10

functions:
  graphql:
    handler: graphql.handler
    events:
      - http:
          path: /
          method: post
          cors: true
